name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 8080
        script: |
          REPO_DIR=/home/ubuntu/YoloService
          REPO_URL=https://github.com/hamad-fyad/yolo-services.git

          # Install Python 3, venv, and pip if not already installed
          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip

          # Clone the repo if it doesn't exist
          if [ ! -d "$REPO_DIR" ]; then
            git clone $REPO_URL $REPO_DIR
          fi

          cd $REPO_DIR
          git pull origin main

          # Setup virtual environment
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
          fi

          source .venv/bin/activate
          pip install -r requirements.txt
          pip install -r torch-requirements.txt

          # Restart the YOLO service
          sudo systemctl daemon-reload
          sudo systemctl enable yolo
          sudo systemctl start yolo
          sudo systemctl status yolo

          